### PR TITLE
feat: support non-namespaced resources

### PR DESCRIPTION
**Pull request by nayihz**
add feat: support non-namespaced resources.
code style: code format by `cargo-fmt`.

### CODE REVIEW

**Comment by imuxin** [comment]
Did it crash when request cluster scoped resource? I remember I had test this case. Anyway this PR lgtm. Thanks, good work!

**Comment by nayihz** [comment]
I test it successfully using `./kubectl-watch node`

**Comment by imuxin** [comment]
Try use `git commit -s` to sign off?

**Comment by nayihz** [comment]
> Try use `git commit -s` to sign off?

Done

**Review by imuxin — APPROVED** [review]

**Pull request merged**
